// https://inlang.com/documentation
export async function defineConfig(env) {
    const plugin = await env.$import("https://cdn.jsdelivr.net/gh/samuelstroschein/inlang-plugin-json@1/dist/index.js");

    const pluginConfig = {
        pathPattern: "./locales/{language}/json.json",
    };

    return {
        referenceLanguage: "en",
        languages: [
            "af",
            "ar",
            "az",
            "be",
            "bg",
            "bn",
            "bs",
            "ca",
            "cs",
            "cy",
            "da",
            "de",
            "de_CH",
            "el",
            "en",
            "es",
            "et",
            "eu",
            "fa",
            "fi",
            "fil",
            "fr",
            "gl",
            "gu",
            "he",
            "hi",
            "hr",
            "hu",
            "hy",
            "id",
            "is",
            "it",
            "ja",
            "ka",
            "kk",
            "km",
            "kn",
            "ko",
            "lt",
            "lv",
            "mk",
            "mn",
            "mr",
            "ms",
            "nb",
            "ne",
            "nl",
            "nn",
            "oc",
            "pl",
            "ps",
            "pt",
            "pt_BR",
            "ro",
            "ru",
            "sc",
            "si",
            "sk",
            "sl",
            "sq",
            "sr_Cyrl",
            "sr_Latn",
            "sr_Latn_ME",
            "sv",
            "sw",
            "tg",
            "th",
            "tk",
            "tl",
            "tr",
            "ug",
            "uk",
            "ur",
            "uz_Cyrl",
            "uz_Latn",
            "vi",
            "zh_CN",
            "zh_HK",
            "zh_TW",
        ],
        readResources: (args) => plugin.readResources({ ...args, ...env, pluginConfig }),
        writeResources: (args) => plugin.writeResources({ ...args, ...env, pluginConfig }),
    };
}
